### ISSUE TITLE
Can this be turned into an exe or a single double click script ? 

### ISSUE THREAD

**Issue by BrLyes** [InventivetalentDev/OCRwatch#2]
**Is your feature request related to a problem? Please describe.**
It's a bit hard to get this running for end users, can this be turned into a single portable exe ? 

**Describe the solution you'd like**
Turning the python scrips into a single exe 

**Describe alternatives you've considered**
Maybe not an exe but something that a user can just double click and get it up and running maybe a batch script ? but then you'd have to handle the python dependencies 

**Additional context**
NA

**Comment by InventivetalentDev** [comment]
I can look into that!

**Comment by InventivetalentDev** [comment]
just published a release with an executable :)

**Comment by BrLyes** [comment]
Great stuff! 

I had to manually install pyinstaller via 
`pip install -U pyinstaller`
But other than that it works nicely, thank you!
