### ISSUE TITLE
Support different resolutions

### ISSUE THREAD

**Issue by BrLyes** [InventivetalentDev/OCRwatch#3]
**Is your feature request related to a problem? Please describe.**
It seems that the Ocr can only read 1920x1080 resolution and it will crash if the resolution is different

**Describe the solution you'd like**
The screenshot taken should auto-resize to the supported resolution. 

I mange to get this working by editing the screenshot.py and add: 
` image = Image.open(f"monitor-{monitor}.png")`
` image.thumbnail((1920,1080), Image.ANTIALIAS)`
`image.save(f"monitor-{monitor}.png","png")`

After 

`with mss() as sct:`
`sct.shot(mon=monitor)`
        
And 
`from PIL import Image`

Note that i only tested this on 2K resolution, think it wont work properly on aspect ratio different than 16:9

**Describe alternatives you've considered**

It should be possible to gather all possible positions for the OCR for all different resolutions but this is such a tideous task... or maybe getting a factor to mult by depending on the width and height but i'm not good enough at Math for that...

**Additional context**
I wanted to raise a PR so you can review it and reduce your workload but got permission denied :p

PS: Can i use this for a custom project i'm working on ? plz :D

**Comment by InventivetalentDev** [comment]
Thanks!    


> PS: Can i use this for a custom project i'm working on ? plz :D  

Sure! Would appreciate credit if you decide to publish it :)

**Comment by BrLyes** [comment]
> Thanks!
> 
> > PS: Can i use this for a custom project i'm working on ? plz :D
> 
> Sure! Would appreciate credit if you decide to publish it :)

Of course! thank you so much
